# Desenvolvimento e acesso de novos métodos e metodologias de ensino e aprendizagem

Nos meses de novembro e dezembro de 2020 pretende-se realizar estudos avançados em metodologias de ensino voltadas para a educação pública. Serão estudadas as metodologias desenvolvidas e utilizadas pela: (1) [Preuss School](https://preuss.ucsd.edu/), escola voltada para a formação de estudantes do ensino fundamental II e médio, de baixa renda, que se esforçam para se tornarem os primeiros em suas famílias a ingressarem na universidade e concluírem o nível superior. Localizado no campus da Universidade da Califórnia San Diego (UCSD), os estudantes têm a oportunidade de utilizar a estrutura universitária da UCSD e vivenciarem um ambiente que os incentiva a tomada de riscos intelectuais, oferecendo uma variedade de apoios acadêmicos. Quase 100% dos seus estudantes ingressam e concluem o nível universitário, concorrendo com estudantes de escolas públicas e privadas; (2) [CREATE](https://create.ucsd.edu/), órgão da UCSD que apoia e promove projetos e ações educacionais visando o desenvolvimento de estudantes e a capacitação de professores, considerando suas necessidades locais, e promovendo o seu acesso à universidade; (3) Lemann Center for Educational Entrepreneurship and Innovation in Brazil da Universidade de Stanford, que apoia uma variedade de projetos de pesquisa e inovação, com foco na melhoria das oportunidades de aprendizagem para estudantes socialmente desfavorecidos dentro e fora do sistema público de ensino; (4) [You Cubed da Universidade de Stanford](https://www.youcubed.org/), grupo de pesquisa cujos projetos visam inspirar, educar e capacitar professores de matemática e transformar as recentes pesquisas sobre matemática em formas acessíveis e práticas; (5) [Transformative Learning Technologies Lab (TLTL) da Universidade de Columbia](https://tltlab.org/), grupo multidisciplinar que projeta e pesquisa novas tecnologias para a educação. Ao final, pretende-se construir propostas de ferramentas e metodologias considerando a realidade do público escolar que faz parte do projeto e das escolas públicas de Salvador e da Bahia. Até então, os seguintes contatos foram realizados:

 - Reunião presencial e troca de e-mails com Tamika Franklin- Diretora de Desenvolvimento da Preuss School. Apresentação do projeto e propostas de futuras parcerias (pós-pandemia), 10/03/2020.
 - Participação do Lemann Center Virtual Meeting da Stanford University. Apresentação dos projetos Meninas na Ciência de Dados e Ciência de Dados na Educação Pública a convite de um dos seus diretores, Prof. Eric Bettinger, 29/09/2020.
 - Reunião virtual com Raquel Coelho, doutoranda em International Compatative Education and in Learning Sciences and Technology Design do Lemann Center for Educational Entrepreneurship and Innovation in Brazil, 14/10/2020.
 - Reunião virtual com Tatiana Hochgreb-Haegeke e Guilherme Desiderio, responsáveis pelo Programa de Especialização Docente Brasil (PED Brasil), apoiado pela Stanford University em parceria com instituições de ensino superior brasileiras, 19/01/2020.
