# Atividade de Fixação

As atividades de fixação com os estudantes foram realizadas entre os meses de Novembro e Dezembro/2020, com o intuito de verificar o ganho de conhecimento dos estudantes e percepção dos conteúdos tratados em problemas contextualizados. As equipes elaboraram a atividade com base nos conteúdos discutidos nas dinâmicas frente às habilidades esperadas. Desta forma, este capítulo irá discutir a percepção de cada equipe sobre os resultados obtidos nas atividades.
As atividades foram elaboradas no Google Forms e disponibilizadas aos estudantes no horário da dinâmica realizada no Google Meet, após as instruções das equipes. O período de avaliação foi configurado para 40 minutos a partir do momento de abertura do link. Após este tempo novas respostas não foram aceitas. 

 **Sugestão: depois que todas as equipes inserirem suas atividades, sugiro um quadro com as informações dia da atividade, quantidade de alunos que realizaram, quantidade de questões por equipe e na ordem de apresentação dos itens a seguir. ou no final com mais uma coluna com as considerações gerais por equipe.** 
 
## Ciência de Dados

A atividade proposta pela equipe de Ciência de Dados foi realizada no dia 20/11. Para nortear a elaboração dos questionários, o documento da Unesco e EDC (Oceans of Data) foram utilizados como referência na definição das habilidades esperadas para cientistas de dados. Diante das habilidades indicadas nos materiais e os conteúdos discutidos nos encontros, a equipe definiu como elementos mais relevantes para verificar o ganho de conhecimento pelos estudantes a coleta de dados critica, solução analítica de problemas, métodos estatísticos, contextualização dos conteúdos e a proteção de privacidade de dados. 

Foram desenvolvidas 03 questões de múltipla escolha com os seguintes objetivos:

 - Questão 1: Identificar um dado e suas fontes, percepção da privacidade de dados.  
 - Questão 2: Perceber o viés amostral e a identificação das medidas de tendência central para generalizar resultados. 
 - Questão 3: Identificação de métrica estatística para generalização de resultados, considerando análise crítica. 


### Questão 1 {-}

 a. A Ciência de Dados tem um enorme potencial para lidar com diferentes tipos de problemas, por isso é aplicada a diversas áreas do conhecimento. São muitos os desafios que os cientistas de dados enfrentam para obter informações que auxiliem a tomada de decisão. Imagine que você acabou de ser contratada (o) como Cientista de Dados e deve responder às seguintes perguntas:



