# Desafios e Oportunidades {#conclusaogeral}

Considerando o contexto geral no qual o projeto tem sido desenvolvido, podemos 
ainda considerar alguns desafios e oportunidades para os diferentes atores do 
projeto.

## Desafios 

### Para as Estudantes {-}

Limite de acesso a equipamentos eletrônicos e conexão à internet durante a pandemia prejudica a assiduidade nas reuniões, a interação com colegas e facilitadores durante os encontros online e a realização de tarefas ▪ Ambiente doméstico pouco propício ao estudo e engajamento nas reuniões online acentua a dispersão e prejudica o aprendizado ▪ Necessidade de conciliar engajamento no projeto ao desempenho de tarefas domésticas e trabalho informal ▪ Frágil formação escolar prejudica leitura e interpretação de conteúdos apresentados pelo projeto ▪ Timidez; dificuldade para elaborar e expressar opiniões e pensamentos por escrito e/ou verbalmente ▪  Acompanhamento/apoio frágil por parte dos pais ou responsáveis.

### Para as/os Professores/as {-}

Necessidade de desenvolver habilidades para utilização de plataformas de videoconferências ▪ Receio para a condução de disciplina de Inteligência Artificial, devido aos novos conteúdos abordados ▪ Dificuldade de vincular os conteúdos discutidos às disciplinas específicas que lecionam ▪ Dificuldade na compreensão da língua inglesa. 

### Para a Equipe {-}

Adaptação ao ambiente virtual de ensino e interação com as/os estudantes ▪ Apropriação de conhecimentos transversais à formação da equipe multidisciplinar ▪ Construção de conteúdos em uma linguagem compreensível e atrativa ao público-alvo ▪ Alinhamento das ações e discursos com apoio de professoras/es ainda em formação nas áreas de atuação do Projeto ▪ Delineamento de ferramentas de avaliação quantitativas que considerem o ganho de habilidades e a complexidade da formação de cidadãos como protagonistas sociais ▪ Estabelecimento do escopo inicial do projeto devido pandemia ou a novas oportunidades. 

## Oportunidades

Estudo e proposição de métodos e metodologias de ensino online e presencial ▪ Delineamento de ferramentas e plano de avaliação quantitativa de impactos do projeto e execução da avaliação ▪ Elaboração de E-books voltados para estudantes e professoras/es ▪ Levantamento de dados e propostas de abordagens temáticas para as disciplinas em sala de aula, junto às/aos professores e estudantes das escolas do projeto ▪ Desenvolvimento das atividades de liderança dos professores para ensino baseado nos conteúdos do e-book sobre Protagonismo Social, Racial e de Gênero e no uso do site (re)Conhecendo Salvador ▪ Encantamento de novas/os estudantes e professoras/es ▪ Encantamento e aproximação dos pais ou responsáveis ▪ Expansão das ações de capacitação de professores para demais docentes do estado da Bahia ▪ Fortalecimento da aproximação com líderes das comunidades ▪ Solidificação e construção de parcerias ▪ Contribuição para a produção de conhecimento na universidade por meio da elaboração e publicação de artigos científicos.

